# Generated by Django 5.1.3 on 2025-01-04 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_otpmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('expense_catogary', models.CharField(choices=[('food', 'Food'), ('movie', 'Movie'), ('Shoping', 'Shopping'), ('travel', 'Travel'), ('others', 'Others')])),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('cash', 'CASH')], null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentmaster')),
            ],
            options={
                'db_table': 'expense_master',
            },
        ),
    ]
