# Generated by Django 5.1.3 on 2025-01-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otpmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
